// `.env.ts` is generated by the `npm run env` command
import env from './.env';
/**
* we can add more environment related variables like API's baseurl
*/
export const environment = {
  production: true,
  serverUrl: 'http://localhost:3000',
  defaultLanguage: 'en-US',
  defaultUserName: 'Guest',
  supportedLanguages: [
    'en-US',
    'ar-EG'
  ]
};
