// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  serverUrl: 'http://localhost:3000',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'ar-EG'
  ]
};
